import { useState } from 'react'
import { Link } from 'react-router-dom'
import { profileData, type ProfileOrganization } from '../../data/profileData'
import { prototypeData } from '../../data/prototypeData'
import type { Product } from '../../data/types'
import { useCommerce } from '../../state/CommerceState'
import { useProfile } from '../../state/ProfileState'
import { ProfileDialog } from './ProfileDialog'

function Heading({ title, action }: { title: string; note?: string; action?: React.ReactNode }) {
  return <header className="profile-section__heading"><h1>{title}</h1>{action}</header>
}

function ProductTile({ product, removable = false }: { product: Product; removable?: boolean }) {
  const commerce = useCommerce()
  return <article className="profile-product" data-testid={`profile-product-${product.id}`}><Link to={product.href} className="profile-product__art" aria-label={product.name}><i /><span /></Link><div><small>Артикул: {product.sku}</small><Link to={product.href}><strong>{product.name}</strong></Link><span>{product.availability}</span></div><footer><b>{product.price}</b><div>{removable && <button type="button" aria-label="Удалить из избранного" onClick={() => commerce.removeFavorite(product.id)}>×</button>}<button type="button" aria-label="Добавить в корзину" onClick={() => commerce.addToCart(product.id)}>+</button></div></footer></article>
}

export function ProfileOrganizations() {
  const { organizations, addOrganization } = useProfile(); const [open, setOpen] = useState(false); const [inn, setInn] = useState(''); const [found, setFound] = useState<ProfileOrganization | null>(null)
  const lookup = () => setFound({ id: `org-${Date.now()}`, name: 'ООО «Гараж Профи»', inn: inn || '7600000028', kpp: '760001003', legalAddress: '150003, г. Ярославль, ул. Советская, 17', bank: 'Демонстрационный банк', account: '40702 •••• 0299', active: true })
  return <div className="profile-section"><Heading title="Мои организации" note="Реквизиты и корпоративные заказы" action={<button className="profile-button profile-button--primary" type="button" onClick={() => setOpen(true)}>Добавить организацию</button>} /><p className="profile-info">К аккаунту можно привязать несколько организаций. Управление сотрудниками и ролями в прототип не входит.</p><div className="profile-organization-grid">{organizations.map((org) => <article className="profile-panel profile-organization" key={org.id}><div><span className="profile-status"><i />{org.active ? 'Активна' : 'Требует подтверждения'}</span><h2>{org.name}</h2><small>ИНН {org.inn} · КПП {org.kpp}</small></div><dl><div><dt>Юридический адрес</dt><dd>{org.legalAddress}</dd></div><div><dt>Расчётный счёт</dt><dd>{org.account}</dd></div></dl><Link to="/profile/orders">Заказы организации →</Link></article>)}</div>{open && <ProfileDialog title="Добавить организацию" onClose={() => setOpen(false)}><div className="profile-form"><p>Демонстрационный поиск имитирует автозаполнение реквизитов по ИНН.</p><label>ИНН организации<input value={inn} inputMode="numeric" onChange={(e) => { setInn(e.target.value); setFound(null) }} /></label><button className="profile-button" type="button" onClick={lookup}>Найти по ИНН</button>{found && <div className="profile-lookup"><strong>{found.name}</strong><span>ИНН {found.inn} · КПП {found.kpp}</span><small>{found.legalAddress}</small></div>}{found && <button className="profile-button profile-button--primary" type="button" onClick={() => { addOrganization(found); setOpen(false) }}>Сохранить организацию</button>}</div></ProfileDialog>}</div>
}

export function ProfileFavorites() {
  const commerce = useCommerce(); const products = prototypeData.products.filter((product) => commerce.favoriteIds.has(product.id))
  return <div className="profile-section"><Heading title="Избранное" note="Сохранённые товары" /><p className="profile-section-note">Изменения синхронизированы с избранным в каталоге и счётчиком в шапке.</p>{products.length ? <div className="profile-product-grid">{products.map((product) => <ProductTile key={product.id} product={product} removable />)}</div> : <div className="profile-empty"><span>♡</span><h2>В избранном пока пусто</h2><p>Добавляйте товары из каталога, чтобы вернуться к ним позже.</p><Link className="profile-button profile-button--primary" to="/catalog">Перейти в каталог</Link></div>}</div>
}

export function ProfileRecentlyViewed() {
  const { recentProductIds, clearRecentlyViewed } = useProfile(); const [confirm, setConfirm] = useState(false); const products = recentProductIds.map((id) => prototypeData.products.find((item) => item.id === id)).filter(Boolean) as Product[]
  return <div className="profile-section"><Heading title="Вы смотрели" note="Недавно просмотренные товары" action={products.length ? <button className="profile-button" type="button" onClick={() => setConfirm(true)}>Очистить историю</button> : undefined} />{products.length ? <div className="profile-product-grid">{products.map((product) => <ProductTile key={product.id} product={product} />)}</div> : <div className="profile-empty"><span>◷</span><h2>История просмотров пуста</h2><p>Здесь появятся товары, которые вы недавно открывали.</p><Link className="profile-button profile-button--primary" to="/catalog">Перейти в каталог</Link></div>}{confirm && <ProfileDialog title="Очистить историю просмотров" onClose={() => setConfirm(false)}><p>Удалить весь список недавно просмотренных товаров?</p><div className="profile-actions"><button className="profile-button profile-button--danger" type="button" onClick={() => { clearRecentlyViewed(); setConfirm(false) }}>Очистить</button><button className="profile-button" type="button" onClick={() => setConfirm(false)}>Отмена</button></div></ProfileDialog>}</div>
}

export function ProfileServices() {
  const [selected, setSelected] = useState<(typeof profileData.serviceRequests)[number] | null>(null)
  return <div className="profile-section"><Heading title="Заявки на услуги" note="Обращения и текущие статусы" action={<Link className="profile-button profile-button--primary" to="/services">Новая заявка</Link>} /><div className="profile-request-list">{profileData.serviceRequests.map((request) => <article className="profile-panel profile-request" key={request.id}><div><small>Заявка № {request.id} · {request.date}</small><h2>{request.service}</h2></div><span className="profile-status"><i />{request.status}</span><div><span>{request.city}</span><small>{request.contact}</small></div><button className="profile-link-button" type="button" onClick={() => setSelected(request)}>Подробнее</button></article>)}</div>{selected && <ProfileDialog title={`Заявка № ${selected.id}`} onClose={() => setSelected(null)}><div className="profile-data-lines"><strong>{selected.service}</strong><span>Статус: {selected.status}</span><span>Город: {selected.city}</span><span>Контакт: {selected.contact}</span></div><p>Демонстрационный сценарий показывает историю обращения; переписка и файлы будут уточнены после согласования.</p></ProfileDialog>}</div>
}

export function ProfileReviews() {
  const [editing, setEditing] = useState<string | null>(null); const [message, setMessage] = useState('')
  return <div className="profile-section"><Heading title="Отзывы" note="Ваши отзывы о товарах" /><div className="profile-review-list">{profileData.reviews.map((review) => <article className="profile-panel profile-review" key={review.id}><span className="profile-product__art" aria-hidden="true"><i /><span /></span><div><small>{review.product.sku}</small><h2>{review.product.name}</h2><p>{review.text}</p></div><div><span className="profile-status"><i />{review.status}</span><button className="profile-link-button" type="button" onClick={() => setEditing(review.id)}>Редактировать</button></div></article>)}</div>{editing && <ProfileDialog title="Редактировать отзыв" onClose={() => setEditing(null)}><div className="profile-form"><label>Текст отзыва<textarea defaultValue={profileData.reviews.find((item) => item.id === editing)?.text} /></label><button className="profile-button profile-button--primary" type="button" onClick={() => { setEditing(null); setMessage('Отзыв сохранён и отправлен на модерацию') }}>Сохранить отзыв</button></div></ProfileDialog>}{message && <p className="profile-message profile-message--success" role="status">{message}</p>}</div>
}

export function ProfileData() {
  const { user, updateUser } = useProfile(); const [draft, setDraft] = useState(user); const [message, setMessage] = useState('')
  return <div className="profile-section"><Heading title="Профиль" note="Личные данные и адреса" />{message && <p className="profile-message profile-message--success" role="status">{message}</p>}<div className="profile-detail-grid"><section className="profile-panel"><div className="profile-panel-heading"><h2>Личные данные</h2><span>Телефон подтверждён</span></div><div className="profile-form profile-form--grid"><label>Имя<input value={draft.firstName} onChange={(e) => setDraft({ ...draft, firstName: e.target.value })} /></label><label>Фамилия<input value={draft.lastName} onChange={(e) => setDraft({ ...draft, lastName: e.target.value })} /></label><label>Телефон<input value={draft.phone} onChange={(e) => setDraft({ ...draft, phone: e.target.value })} /></label><label>Электронная почта<input type="email" value={draft.email} onChange={(e) => setDraft({ ...draft, email: e.target.value })} /></label><button className="profile-button profile-button--primary" type="button" onClick={() => { updateUser(draft); setMessage('Данные профиля сохранены') }}>Сохранить данные</button></div></section><section className="profile-panel"><div className="profile-panel-heading"><h2>Адреса доставки</h2><button className="profile-link-button" type="button" onClick={() => setMessage('Добавление адреса показано в демонстрационном режиме')}>Добавить</button></div><div className="profile-address-list">{profileData.addresses.map((address, index) => <div key={address}><span>{index === 0 ? 'Основной адрес' : 'Рабочий адрес'}</span><strong>{address}</strong><button className="profile-link-button" type="button">Изменить</button></div>)}</div></section></div></div>
}
