import { useEffect, useRef, useState, type FormEvent } from 'react'

export function ContactDialog({ mode, onClose }: { mode: 'consultation' | 'callback'; onClose(): void }) {
  const [name, setName] = useState(''); const [contact, setContact] = useState(''); const [submitted, setSubmitted] = useState(false); const [attempted, setAttempted] = useState(false)
  const headingRef = useRef<HTMLHeadingElement>(null)
  useEffect(() => { headingRef.current?.focus(); const key = (event: KeyboardEvent) => event.key === 'Escape' && onClose(); window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) }, [onClose])
  const submit = (event: FormEvent) => { event.preventDefault(); setAttempted(true); if (name.trim() && contact.trim()) setSubmitted(true) }
  return <div className="overlay"><section className="dialog contact-dialog" role="dialog" aria-modal="true" aria-labelledby="contact-title"><button className="dialog__close" aria-label="Закрыть форму" onClick={onClose}>×</button>{submitted ? <div className="contact-success"><span aria-hidden="true">✓</span><h2 id="contact-title" tabIndex={-1} ref={headingRef}>Спасибо! Ваше сообщение отправлено</h2><p>Мы свяжемся с вами по указанному контакту.</p><button className="button" onClick={onClose}>Закрыть</button></div> : <form onSubmit={submit}><p className="eyebrow">{mode === 'callback' ? 'Обратный звонок' : 'Консультация специалиста'}</p><h2 id="contact-title" tabIndex={-1} ref={headingRef}>{mode === 'callback' ? 'Когда вам удобно поговорить?' : 'Расскажите, с чем помочь'}</h2><div className="form-field"><label htmlFor="contact-name">Ваше имя</label><input id="contact-name" value={name} onChange={(event) => setName(event.target.value)} aria-describedby={attempted && !name.trim() ? 'name-error' : undefined} />{attempted && !name.trim() && <span id="name-error" className="field-error">Укажите имя</span>}</div><div className="form-field"><label htmlFor="contact-value">Телефон или электронная почта</label><input id="contact-value" value={contact} onChange={(event) => setContact(event.target.value)} aria-describedby={attempted && !contact.trim() ? 'contact-error' : undefined} />{attempted && !contact.trim() && <span id="contact-error" className="field-error">Укажите контакт</span>}</div><div className="form-field"><label htmlFor="contact-comment">Комментарий</label><textarea id="contact-comment" rows={3} /></div><button className="button button--dark" type="submit">Отправить запрос</button></form>}</section></div>
}
